language: perl
sudo: false
perl:
  - "5.30.0"
matrix:
  include:
    - perl: "5.10.1"
      before_install:
        - perlbrew install-patchperl
        - perlbrew install perl-5.10.1
        - perlbrew use perl-5.10.1
env: 
  - RELEASE_TESTING=1
script:
  - perlbrew available
  - perlbrew list
  - perl Makefile.PL && make test RELEASE_TESTING=1

