language: perl
sudo: false
perl:
  - "5.30.0"
  - "5.28.2"
  - "5.24.3"
matrix:
  include:
    - perl: "5.10.1"
      before_install:
        - perlbrew install -j4 perl-5.10.1 || (cat /home/travis/perl5/perlbrew/build.perl-5.10.1.log && exit 1)
        - perlbrew use perl-5.10.1
env: 
  - RELEASE_TESTING=1
script:
  - perlbrew available
  - perlbrew list
  - perl Makefile.PL && make test RELEASE_TESTING=1

